
package com.epam.lab.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CopterRemoteControllerImplService", targetNamespace = "http://service.lab.epam.com/", wsdlLocation = "http://localhost:8080/YuriiPasternakSOAPService/copterService?wsdl")
public class CopterRemoteControllerImplService
    extends Service
{

    private final static URL COPTERREMOTECONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COPTERREMOTECONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName COPTERREMOTECONTROLLERIMPLSERVICE_QNAME = new QName("http://service.lab.epam.com/", "CopterRemoteControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/YuriiPasternakSOAPService/copterService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COPTERREMOTECONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        COPTERREMOTECONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public CopterRemoteControllerImplService() {
        super(__getWsdlLocation(), COPTERREMOTECONTROLLERIMPLSERVICE_QNAME);
    }

    public CopterRemoteControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COPTERREMOTECONTROLLERIMPLSERVICE_QNAME, features);
    }

    public CopterRemoteControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, COPTERREMOTECONTROLLERIMPLSERVICE_QNAME);
    }

    public CopterRemoteControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COPTERREMOTECONTROLLERIMPLSERVICE_QNAME, features);
    }

    public CopterRemoteControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CopterRemoteControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CopterRemoteControllerImpl
     */
    @WebEndpoint(name = "CopterRemoteControllerImplPort")
    public CopterRemoteControllerImpl getCopterRemoteControllerImplPort() {
        return super.getPort(new QName("http://service.lab.epam.com/", "CopterRemoteControllerImplPort"), CopterRemoteControllerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopterRemoteControllerImpl
     */
    @WebEndpoint(name = "CopterRemoteControllerImplPort")
    public CopterRemoteControllerImpl getCopterRemoteControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.lab.epam.com/", "CopterRemoteControllerImplPort"), CopterRemoteControllerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COPTERREMOTECONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw COPTERREMOTECONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return COPTERREMOTECONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
