
package com.epam.lab.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalPositionException", targetNamespace = "http://service.lab.epam.com/")
public class IllegalPositionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SeviceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IllegalPositionException(String message, SeviceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IllegalPositionException(String message, SeviceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epam.lab.service.SeviceFault
     */
    public SeviceFault getFaultInfo() {
        return faultInfo;
    }

}
